### ISSUE TITLE
RpcModule.run initServer failed in chainbox mail-example

### ISSUE THREAD

**Issue by nmschorr** [nuls-io/nuls-chainbox#6]
The mail example is failing suddenly. The front end comes up and sends the request, but nothing returns. Kathy is having the same problem.

Here's the error from nuls-chainbox/NULS_WALLET/Logs/mail-example/stdout.log:

2019-09-07 23:47:15.347  [main] ERROR - io.nuls.core.rpc.modulebootstrap.RpcModule.run(RpcModule.java:226):{"name":"mail-example","version":"1.0"} initServer failed
java.lang.Exception: 向核心注册失败！
	at io.nuls.core.rpc.netty.processor.ResponseMessageProcessor.syncKernel(ResponseMessageProcessor.java:154)
	at io.nuls.core.rpc.modulebootstrap.RpcModule.run(RpcModule.java:216)
	at io.nuls.core.rpc.modulebootstrap.NulsRpcModuleBootstrap.run(NulsRpcModuleBootstrap.java:81)
	at io.nuls.NulsModuleBootstrap.main(NulsModuleBootstrap.java:30)
/home/admin/dev/cb7/nuls-chainbox/NULS_WALLET/Logs/mail-example->

**Comment by nmschorr** [comment]
Kathy asked me to do a refresh. I just re-cloned the nuls-chainbox repository.  Also did the requested 'git pull origin master' which resulted in :
/home/admin/dev/ncc/nuls-chainbox-> git pull origin master
From github.com:nuls-io/nuls-chainbox
 * branch            master     -> FETCH_HEAD
Already up-to-date.

It's still producing the above exception in the stdout.log.

**Comment by nmschorr** [comment]
Here's what the check-status tool shows:
![check-status](https://user-images.githubusercontent.com/12592910/64590648-e2617300-d35c-11e9-9230-bd32af7f7b4b.jpg)

**Comment by nmschorr** [comment]
Chainbox stdut.log:

![chainbox-bug-stdut log](https://user-images.githubusercontent.com/12592910/64591720-50a73500-d35f-11e9-916b-2515448dc7c5.jpg)

**Comment by nmschorr** [comment]
By the way -  others have copied this chainbox repo for the Hackathon and modified it, including myself. :)  I'm not sure what to do if files keep changing.  I can update the local files, but I've already modified the build scripts for my own project.  Hoping the build scripts aren't changing too.

I would like to have my project point to a 'frozen' nuls parent.  Perhaps you could consider having two or more release channels like "development" and "production".  The production channel should be archived regularly - with minor version numbers - so people can fetch the version their stuff is based on.

**Comment by nmschorr** [comment]
This was fixed awhile ago. I'll try to close it.

**Comment by nmschorr** [comment]
Bug has gone away. Thanks!
